In [5]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.datasets import load_boston
df=load_boston()
df.keys()
print(df.data)
boston=pd.DataFrame(df.data,columns=df.feature_names)
boston.head()
boston['MEDV']=df.target
boston.head()
boston.isnull()
boston.isnull().sum()
from sklearn.model_selection import train_test_split
x=boston.drop('MEDV',axis=1)
y=boston['MEDV']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
x=boston.drop('MEDV',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=5)
lin_model=LinearRegression()
lin_model.fit(x_train,y_train)
y_train_predict=lin_model.predict(x_train)
rmse=(np.sqrt(mean_squared_error(y_train,y_train,y_train_predict)))
print("this model perfomance for training set")
print('RMSE is {}'.format(rmse))
print("\n")
y_test_predict=lin_model.predict(x_test)
rmse=(np.sqrt(mean_squared_error(y_test,y_test_predict)))
print("this model performance for training set")
print('RMSE is {}'.format(rmse))

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(430, 13)
(76, 13)
(430,)
(76,)
this model perfomance for training set
RMSE is 0.0


this model performance for training set
RMSE is 4.687543527902972
